### ISSUE TITLE
Websocket exception not caught

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#261]
### Version of this library.

1.40.5

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

VPS or other cloud hosting

### Operating System?

Linux

### Python version?

Python3.8

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

Hello,

I am using the exact same config as in #235 and the same code basically.

Since version 1.40.5, I noticed that while I am streaming data via the websockets, there is now that message that pops. It does not seem to affect the reconnexion of the websocket, but it does make the logs pretty bad-looking x) Do you plan on keeping it as it currently is, or wouldn't it be better to catch this?

```
Task exception was never retrieved
future: <Task finished name='Task-237' coro=<BinanceWebSocketApiSocket.start_socket() done, defined at /home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py:63> exception=Sy
stemExit(1)>
Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 115, in start_socket
    received_stream_data_json = await websocket.receive()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/connection.py", line 280, in receive
    received_data_json = await self.manager.websocket_list[self.stream_id].recv()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/manager.py", line 525, in _create_stream_thread
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 211, in start_socket
    sys.exit(1)
SystemExit: 1
```

**Comment by oliver-zehentleitner** [comment]
The error is catched, i think this output is produced by the use of `sys.exit(1)`. I must test, maybe we can switch to `os._exit(1)` which shoukld not be shown up as a error stack in the log files

**Comment by CharlyEmpereurmot** [comment]
Makes sense. Otherwise, everything seems to work perfectly fine, websockets are stable in the long run and reconnect quickly when necessary :)

**Comment by CharlyEmpereurmot** [comment]
Sorry there was the 2 first lines missing in this error log, I have edited the 1st post to include everything properly. There is nothing else that displays. But I had disabled the logger like this:

```
import logging
logger = logging.getLogger()
logger.disabled = True
```

**Comment by CharlyEmpereurmot** [comment]
Then sometimes the trace is slightly different and the sys.exit() happens at a different line:

```
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<BinanceWebSocketApiSocket.start_socket() done, defined at /home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py:63> exception=Sys
temExit(1)>
Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 115, in start_socket
    received_stream_data_json = await websocket.receive()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/connection.py", line 280, in receive
    received_data_json = await self.manager.websocket_list[self.stream_id].recv()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/manager.py", line 525, in _create_stream_thread
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 204, in start_socket
    sys.exit(1)
SystemExit: 1
```

**Comment by oliver-zehentleitner** [comment]
no, os._exit() is not a solution, it breaks the reconnect handling logic and i dont want to touch that. We must catch the exception within the lib in outter code.  

```
unicorn_binance_websocket_api/manager.py", line 525, in _create_stream_thread
    loop.run_forever()

```
seems to be the right place for that.

**Comment by oliver-zehentleitner** [comment]
This works on my side, but we have to monitor and observe this. if you want you can test with me and give feedback. just install the dev-stage: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api#from-the-latest-source-dev-stage-with-pip-from-github

**Comment by CharlyEmpereurmot** [comment]
That sounds good thanks, I will run that!

**Comment by CharlyEmpereurmot** [comment]
Hi Oliver,

I am using the dev-stage, installed like this:
`pip install https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/tarball/master --upgrade`

I think the websockets disco/reco correctly, but now my logs are full of this stack:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-771' coro=<BinanceWebSocketApiSocket.start_socket() done, defined at /home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py:64> exception=Sy
stemExit(1)>
Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 69, in start_socket
    async with BinanceWebSocketApiConnection(self.manager,
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/connection.py", line 133, in __aenter__
    self.manager.websocket_list[self.stream_id] = await self._conn.__aenter__()
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/home/charlyvps/.local/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/manager.py", line 526, in _create_stream_thread
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/charlyvps/.local/lib/python3.8/site-packages/unicorn_binance_websocket_api/sockets.py", line 252, in start_socket
    sys.exit(1)
SystemExit: 1
```

**Comment by oliver-zehentleitner** [comment]
Thank you.

I'll open this again, still takes time to get a final and well tested version

**Comment by oliver-zehentleitner** [comment]
I think the next version will be fine, i release it today
