### ISSUE TITLE
BinanceWebSocketApiManager.stream_is_crashing + websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received + SystemExit: 1

### ISSUE THREAD

**Issue by KissCoderr** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#266]
### Version of this library.

It is the most recent version. 

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

VPS or other cloud hosting

### Operating System?

Linux

### Python version?

Python3.8

### Installed packages

```shell
aiohttp                       3.7.4.post0
aiosignal                     1.2.0
aniso8601                     9.0.1
async-timeout                 3.0.1
attrs                         19.3.0
Automat                       0.8.0
backports.zoneinfo            0.2.1
blinker                       1.4
btcturk-api                   1.8.1
certifi                       2019.11.28
chardet                       3.0.4
charset-normalizer            2.0.12
cheroot                       8.6.0
click                         8.0.4
cloud-init                    21.4
colorama                      0.4.3
command-not-found             0.3
configobj                     5.0.6
constantly                    15.1.0
cryptography                  2.8
dateparser                    1.1.1
dbus-python                   1.2.16
distro                        1.4.0
distro-info                   0.23ubuntu1
entrypoints                   0.3
et-xmlfile                    1.1.0
Flask                         2.0.3
Flask-RESTful                 0.3.9
frozenlist                    1.3.0
httplib2                      0.14.0
hyperlink                     19.0.0
idna                          2.8
importlib-metadata            1.5.0
incremental                   16.10.1
itsdangerous                  2.1.1
jaraco.functools              3.5.0
Jinja2                        3.0.3
jsonpatch                     1.22
jsonpointer                   2.0
jsonschema                    3.2.0
keyring                       18.0.1
language-selector             0.1
launchpadlib                  1.10.13
lazr.restfulclient            0.14.2
lazr.uri                      1.0.3
MarkupSafe                    2.1.1
more-itertools                4.2.0
multidict                     6.0.2
netifaces                     0.10.4
numpy                         1.22.3
oauthlib                      3.1.0
openpyxl                      3.0.9
pandas                        1.4.2
pathlib                       1.0.1
pexpect                       4.6.0
pip                           20.0.2
psutil                        5.9.0
pyasn1                        0.4.2
pyasn1-modules                0.2.1
PyGObject                     3.36.0
PyHamcrest                    1.9.0
PyJWT                         1.7.1
pymacaroons                   0.13.0
PyNaCl                        1.3.0
pyOpenSSL                     19.0.0
pyparted                      3.11.2
pyrsistent                    0.15.5
pyserial                      3.4
python-apt                    2.0.0+ubuntu0.20.4.7
python-binance                1.0.15
python-dateutil               2.8.2
python-debian                 0.1.36ubuntu1
pytz                          2022.1
pytz-deprecation-shim         0.1.0.post0
PyYAML                        5.3.1
regex                         2022.3.2
requests                      2.22.0
requests-unixsocket           0.2.0
SecretStorage                 2.3.1
service-identity              18.1.0
setuptools                    45.2.0
simplejson                    3.16.0
six                           1.14.0
sos                           4.2
ssh-import-id                 5.10
systemd-python                234
Twisted                       18.9.0
typing-extensions             4.1.1
tzdata                        2022.1
tzlocal                       4.1
ubuntu-advantage-tools        27.6
ufw                           0.36
ujson                         5.1.0
unattended-upgrades           0.1
unicorn-binance-websocket-api 1.40.7
unicorn-fy                    0.12.2
urllib3                       1.25.8
wadllib                       1.3.3
WALinuxAgent                  2.2.46
websocket-client              1.3.1
websockets                    10.2
Werkzeug                      2.0.3
wheel                         0.34.2
yarl                          1.7.2
zipp                          1.0.0
zope.interface                4.7.1
```

### Logging output

```shell
BinanceWebSocketApiManager.stream_is_crashing(495461ad869f-4902-40c8-136d-c37cad6a)
Task exception was never retrieved
future: <Task finished name='Task-421157427' coro=<BinanceWebSocketApiSocket.start_socket() done, defined at /usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/sockets.py:63> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 955, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/sockets.py", line 115, in start_socket
    received_stream_data_json = await websocket.receive()
  File "/usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/connection.py", line 280, in receive
    received_data_json = await self.manager.websocket_list[self.stream_id].recv()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/manager.py", line 525, in _create_stream_thread
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/sockets.py", line 204, in start_socket
    sys.exit(1)
SystemExit: 1
```

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

I am having a problem with bookTicker stream. Stream is crashing and it is not reconnecting. Can't find a solution whatever ı tried. 

***Crashing***
BinanceWebSocketApiManager.stream_is_crashing(495461ad869f-4902-40c8-136d-c37cad6a)
Task exception was never retrieved
future: <Task finished name='Task-421157427' coro=<BinanceWebSocketApiSocket.start_socket() done, defined at /usr/local/lib/python3.8/dist-packages/unicorn_binance_websocket_api/sockets.py:63> exception=SystemExit(1)>

***connection error***
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

***cannot restart ***
in start_socket
    sys.exit(1)
SystemExit: 1

**Comment by Ulisses1478** [comment]
Me too

**Comment by oliver-zehentleitner** [comment]
In the next version this should be fixed! (released in the next couple of hours)
