### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by lr2bmail** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#323]
### Version of this library.

1.45.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.8

### Installed packages

```shell
aiohttp                       3.8.4
aiosignal                     1.3.1
alembic                       0.9.6
amqp                          2.6.1
aniso8601                     9.0.1
anyio                         3.6.2
asn1crypto                    1.5.1
async-timeout                 4.0.2
attrdict                      2.0.1
attrs                         20.2.0
Authlib                       0.15.6
autobahn                      20.7.1
Automat                       20.2.0
Babel                         2.8.0
base58                        2.1.1
bcrypt                        3.2.0
beautifulsoup4                4.7.1
billiard                      3.6.3.0
bleach                        3.3.0
blinker                       1.4
CacheControl                  0.12.6
cachelib                      0.9.0
cachetools                    4.2.1
celery                        4.4.7
certifi                       2020.6.20
cffi                          1.14.2
chardet                       3.0.4
charset-normalizer            3.1.0
cheroot                       9.0.0
click                         7.1.2
coinbase-commerce             1.0.1
coincurve                     18.0.0
colorama                      0.4.6
constantly                    15.1.0
croniter                      0.3.34
cryptography                  3.1
cytoolz                       0.12.1
dateparser                    0.7.6
ecdsa                         0.18.0
eth-abi                       2.2.0
eth-account                   0.4.0
eth-hash                      0.5.1
eth-keyfile                   0.5.1
eth-keys                      0.2.4
eth-rlp                       0.2.1
eth-typing                    2.3.0
eth-utils                     1.9.5
firebase-admin                4.5.2
Flask                         1.1.2
Flask-Babel                   2.0.0
Flask-BasicAuth               0.2.0
Flask-Caching                 2.0.2
Flask-Compress                1.4.0
Flask-Cors                    3.0.10
Flask-Executor                0.9.3
Flask-Limiter                 2.0.1
Flask-Login                   0.4.1
Flask-Mail                    0.9.1
Flask-Migrate                 2.1.1
Flask-Moment                  0.10.0
Flask-QRcode                  3.0.0
Flask-ReCaptcha               0.4.2
Flask-RESTful                 0.3.9
Flask-RQ2                     18.3
Flask-Script                  2.0.6
Flask-SQLAlchemy              2.3.2
flower                        0.9.7
frozenlist                    1.3.3
future                        0.18.2
google-api-core               1.26.1
google-api-python-client      2.0.2
google-auth                   1.27.1
google-auth-httplib2          0.1.0
google-cloud-core             1.6.0
google-cloud-firestore        2.0.2
google-cloud-storage          1.36.2
google-crc32c                 1.1.2
google-resumable-media        1.2.0
googleapis-common-protos      1.53.0
grpcio                        1.51.1
gunicorn                      20.0.4
h11                           0.14.0
hexbytes                      0.3.0
httpcore                      0.16.3
httplib2                      0.19.0
httpx                         0.23.3
humanize                      3.5.0
hyperlink                     20.0.1
idna                          2.10
imgurpython                   1.1.7
importlib-metadata            6.0.0
incremental                   17.5.0
IP2Location                   8.0.3
itsdangerous                  1.1.0
jaraco.functools              3.5.2
Jinja2                        2.11.3
jsonpickle                    1.4.1
kombu                         4.6.11
limits                        2.4.0
Mako                          1.1.3
MarkupSafe                    1.1.1
more-itertools                9.0.0
msgpack                       1.0.2
multidict                     6.0.4
natsort                       7.0.1
oauthlib                      3.1.0
packaging                     20.9
paramiko                      2.7.2
parsimonious                  0.8.1
paypal-checkout-serversdk     1.0.1
paypalhttp                    1.0.0
paypalrestsdk                 1.13.1
Pillow                        7.2.0
pip                           21.1.2
prometheus-client             0.8.0
proto-plus                    1.18.0
protobuf                      3.15.6
psutil                        5.9.4
pyaes                         1.6.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
pycryptodome                  3.17
PyHamcrest                    2.0.2
PyJWT                         2.0.1
PyMySQL                       0.10.1
PyNaCl                        1.4.0
pyOpenSSL                     19.1.0
pyparsing                     2.4.7
pysftp                        0.2.8
PySocks                       1.7.1
pyTelegramBotAPI              3.7.7
python-binance                1.0.17
python-dateutil               2.8.1
python-digitalocean           1.15.0
python-editor                 1.0.4
python-slugify                7.0.0
python-socks                  1.2.4
python-twitter                3.5
pytz                          2020.1
qrcode                        6.1
redis                         3.5.3
regex                         2023.3.23
requests                      2.24.0
requests-oauthlib             1.3.0
rfc3986                       1.5.0
rlp                           1.2.0
rq                            0.13.0
rq-scheduler                  0.10.0
rsa                           4.6
service-identity              18.1.0
setuptools                    57.0.0
six                           1.15.0
sniffio                       1.3.0
soupsieve                     2.0.1
SQLAlchemy                    1.1.15
stripe                        2.51.0
Telethon                      1.16.4
text-unidecode                1.3
toolz                         0.12.0
tornado                       6.1
tradingview-ta                3.2.3
tronapi                       3.1.6
tronpy                        0.4.0
trx-utils                     1.0.4
Twisted                       21.2.0
twisted-iocpsupport           1.0.2
txaio                         20.4.1
tzlocal                       2.1
ujson                         5.7.0
unicorn-binance-rest-api      1.8.1
unicorn-binance-websocket-api 1.45.1
unicorn-fy                    0.12.2
uritemplate                   3.0.1
urllib3                       1.25.10
vine                          1.3.0
webencodings                  0.5.1
websocket-client              1.5.0
websockets                    10.4
Werkzeug                      1.0.1
wheel                         0.36.2
yarl                          1.8.2
zipp                          3.1.0
zope.interface                5.1.0
```

### Logging output

```shell
Traceback (most recent call last):
  File "#####/demo.py", line 36, in <module>
    from unicorn_binance_websocket_api.manager import BinanceWebSocketApiManager
  File "#######\venv\lib\site-packages\unicorn_binance_websocket_api\__init__.py", line 3, in <module>
    from unicorn_binance_websocket_api.manager import BinanceWebSocketApiManager
  File "#######\venv\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 36, in <module>
    from unicorn_binance_websocket_api.connection_settings import CEX_EXCHANGES, DEX_EXCHANGES, CONNECTION_SETTINGS
  File "#######\venv\lib\site-packages\unicorn_binance_websocket_api\connection_settings.py", line 50, in <module>
    CONNECTION_SETTINGS: dict[str, Tuple[MAX_SUBSCRIPTIONS_PER_STREAM, WEBSOCKET_BASE_URI, WEBSOCKET_API_BASE_URI]] = {
TypeError: 'type' object is not subscriptable
```

### Processing method?

stream_buffer

### Used endpoint?

concerns all

### Issue

when i try to  run **example_kline_1m_with_unicorn_fy.py**  i get
` TypeError: 'type' object is not subscriptable `

Python 3.8.7 on win11
Python 3.8.10 on Ubuntu 20.04.5

**no error with 1.42.0 or below**

**Comment by oliver-zehentleitner** [comment]
Test with python 3.7 was now successfull: Python 3.7+ should be fixed!
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/actions/runs/4653412934/jobs/8234263910#step:5:28

Please update to: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/releases/tag/1.45.2
