### ISSUE TITLE
exception for error 403 not possible 

### ISSUE THREAD

**Issue by aleangelin88** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#330]
### Version of this library.

unicorn-binance-rest-api      1.9.0
unicorn-binance-websocket-api 1.46.0

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.10

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

users need a way to catch this exception to wait for restriction to be lifted and reconnect

Exception in thread frequent_checks:
Traceback (most recent call last):
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 769, in _frequent_checks
    self.restclient.keepalive_listen_key(stream_id)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_websocket_api\restclient.py", line 291, in keepalive_listen_key
    ubra = BinanceRestApiManager(api_key=self.api_key, api_secret=self.api_secret,
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 370, in __init__
    self.ping()
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 769, in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 542, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 494, in _request_api
    return self._request(method, uri, signed, throw_exception=throw_exception, **kwargs)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 489, in _request
    return self._handle_response(throw_exception=throw_exception)
  File "C:\Users\alean\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn_binance_rest_api\manager.py", line 535, in _handle_response
    raise BinanceAPIException(self.response)
unicorn_binance_rest_api.exceptions.BinanceAPIException: APIError(code=-1003): Way too much request weight used; IP banned until 1681557119785. Please use WebSocket Streams for live updates to avoid bans.

**Comment by oliver-zehentleitner** [comment]
Thank you, I will add an handling for that issue!

**Comment by oliver-zehentleitner** [comment]
This is a good and important point, the UBWA should act on this. I put it at the top of the list.

**Comment by oliver-zehentleitner** [comment]
Will be fixed with the next release.

**Comment by oliver-zehentleitner** [comment]
Have you been banned because of other activities or because of the keepalive function itself?

**Comment by oliver-zehentleitner** [comment]
Keeping the ListenKey alive has been revised and now runs as an asyncIO task in the event loop of the stream. In the 
  event of an exception due to an IP ban, the time window until the ban is lifted is extracted from the Binance response 
  and now waits until then to continue. 
  
I will release it in the next few hours.
