### ISSUE TITLE
Catching the "exception_if_unrepairable" in main-thread

### ISSUE THREAD

**Issue by avmarko** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#339]
### Version of this library.

version 1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.7

### Installed packages

```shell
aiodns                        1.1.1
aiohttp                       3.8.3
aiosignal                     1.3.1
aniso8601                     8.0.0
asn1crypto                    1.0.1
async-timeout                 4.0.2
asynctest                     0.13.0
attrs                         22.1.0
autobahn                      22.7.1
Automat                       0.8.0
binance-connector             3.0.0rc2
ccxt                          3.0.90
certifi                       2022.12.7
cffi                          1.12.3
chardet                       3.0.4
charset-normalizer            2.1.1
cheroot                       8.2.1
Click                         7.0
coinbase                      2.1.0
colorama                      0.4.1
constantly                    15.1.0
copra                         1.2.9
cryptography                  38.0.3
cycler                        0.10.0
dateparser                    0.7.2
DateTime                      5.1
docopt                        0.6.2
Flask                         1.1.1
Flask-RESTful                 0.3.7
frozenlist                    1.3.3
hyperlink                     21.0.0
idna                          2.8
importlib-metadata            6.6.0
incremental                   22.10.0
itsdangerous                  1.1.0
jaraco.functools              2.0
Jinja2                        2.10.3
kiwisolver                    1.0.1
MarkupSafe                    1.1.1
matplotlib                    3.3.1
more-itertools                7.2.0
multidict                     4.5.2
numpy                         1.19.1
pandas                        1.2.4
pathlib                       1.0.1
Pillow                        9.5.0
pip                           23.1.2
pipenv                        2018.11.26
psutil                        5.9.5
pyasn1                        0.4.8
pyasn1-modules                0.2.7
pycares                       3.0.0
pycparser                     2.19
pycryptodome                  3.17
PyHamcrest                    1.9.0
pymssql                       2.1.4
pyodbc                        4.0.25
pyOpenSSL                     22.1.0
pyparsing                     2.3.1
PySocks                       1.7.1
python-binance                1.0.17
python-dateutil               2.7.5
python-dotenv                 0.10.1
pytz                          2019.3
pywin32                       224
regex                         2019.11.1
requests                      2.28.1
scipy                         1.2.1
seaborn                       0.11.1
service-identity              21.1.0
setuptools                    65.6.3
simplejson                    3.17.0
six                           1.12.0
stomp.py                      4.1.22
Twisted                       22.10.0
twisted-iocpsupport           1.0.2
txaio                         22.2.1
typing_extensions             4.4.0
tzlocal                       2.0.0
ujson                         5.5.0
unicorn-binance-rest-api      1.10.0
unicorn-binance-websocket-api 1.46.1
unicorn-fy                    0.12.2
urllib3                       1.24.1
virtualenv                    16.2.0
virtualenv-clone              0.4.0
websocket-client              1.5.1
websockets                    10.4
Werkzeug                      0.16.0
wheel                         0.34.2
yarl                          1.8.1
zipp                          3.15.0
zope.interface                4.7.1
```

### Logging output

```shell
CONSOLE ERROR: 
--------------
Exception in thread _create_stream_thread:  stream_id=817aa2d5b7e7-df6d-734f-c5ce-1900e29d, time=1683713417.7727058:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 569, in _create_stream_thread
    loop.run_until_complete(socket.start_socket())
  File "C:\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\sockets.py", line 71, in start_socket
    symbols=self.symbols) as websocket:
  File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\connection.py", line 87, in __aenter__
    api=self.manager.stream_list[self.stream_id]['api'])
  File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 1642, in create_websocket_uri
    if self.subscribe_to_stream(stream_id, markets=markets, channels=channels) is False:
  File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 3901, in subscribe_to_stream
    raise StreamRecoveryError("stream_id " + str(stream_id) + ": " + str(error_msg))
unicorn_binance_websocket_api.exceptions.StreamRecoveryError: stream_id 817aa2d5b7e7-df6d-734f-c5ce-1900e29d: The limit of 1024 subscriptions per stream has been exceeded!

LOGFILE:
--------
2023-05-10 13:15:46,820 [CRITICAL] 22812 5712 manager: BinanceWebSocketApiManager.stop_stream_as_crash(e6c2c52f288e-0ec8-4505-aa51-ce46643f) - called by File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 3766, in stop_stream_as_crash
    logger.critical(f"BinanceWebSocketApiManager.stop_stream_as_crash({stream_id}){self.get_debug_log()}")
2023-05-10 13:15:46,821 [CRITICAL] 22812 5712 manager: BinanceWebSocketApiManager.subscribe_to_stream(e6c2c52f288e-0ec8-4505-aa51-ce46643f) Info: The limit of 1024 subscriptions per stream has been exceeded!
2023-05-10 13:15:46,823 [CRITICAL] 22812 5712 manager: BinanceWebSocketApiManager.stream_is_crashing(e6c2c52f288e-0ec8-4505-aa51-ce46643f) - called by File "C:\Python37\lib\site-packages\unicorn_binance_websocket_api\manager.py", line 3800, in stream_is_crashing
    logger.critical(f"BinanceWebSocketApiManager.stream_is_crashing({stream_id}){self.get_debug_log()}")
```

### Processing method?

process_stream_data

### Used endpoint?

concerns all

### Issue

I am experimenting with the parameter "throw_exception_if_unrepairable" of the BinanceWebSocketApiManager. I cause an exception on stream creation, by purposely trying to subscribe more 1024 markets in it. The problem is that while the error is reported on my console (running in OS-shell or via IDLE), it's not caught by the try/except of my main thread. 
I am afraid I may be missing some knowledge about catching async/thread exceptions. 
Maybe my problem is related to this (https://quantlane.com/blog/ensure-asyncio-task-exceptions-get-logged/ ) ? 
I would appreciate if somebody can show me an example or point me the way to look for. Thanks in advance

**Comment by oliver-zehentleitner** [comment]
Hello!

I understand your problem, I have also noticed that exceptions from other threads cannot be caught just like that. 

I have already implemented that exceptions from asyncio loops are sent to the main thread and only thrown there.

We can implement the same procedure for this problem.

**Comment by oliver-zehentleitner** [comment]
Hello!

I've been thinking about it. 

Since the exception occurs in the background, the exception cannot be caught. I think the best solution would be to create a stream_signal via a callback function. 

https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/wiki/%60stream_signal_buffer%60

**Comment by oliver-zehentleitner** [comment]
In 2.3.0 the exception is no longer thrown, instead the stream signal "STREAM_UNREPAIRABLE" is sent (if activated).

https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/wiki/%60stream_signals%60
https://pypi.org/project/unicorn-binance-websocket-api/2.3.0/
