### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by AutoAuto** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#344]
### Version of this library.

1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.10

### Logging output

```shell
Exception in thread frequent_checks:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/manager.py", line 769, in _frequent_checks
    self.restclient.keepalive_listen_key(stream_id)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/restclient.py", line 307, in keepalive_listen_key
    ubra = BinanceRestApiManager(api_key=self.api_key, api_secret=self.api_secret,
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 370, in __init__
    self.ping()
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 769, in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 542, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 494, in _request_api
    return self._request(method, uri, signed, throw_exception=throw_exception, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 489, in _request
    return self._handle_response(throw_exception=throw_exception)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 535, in _handle_response
    raise BinanceAPIException(self.response)
unicorn_binance_rest_api.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
```

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

Exception in thread frequent_checks:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/manager.py", line 769, in _frequent_checks
    self.restclient.keepalive_listen_key(stream_id)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/restclient.py", line 307, in keepalive_listen_key
    ubra = BinanceRestApiManager(api_key=self.api_key, api_secret=self.api_secret,
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 370, in __init__
    self.ping()
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 769, in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 542, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 494, in _request_api
    return self._request(method, uri, signed, throw_exception=throw_exception, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 489, in _request
    return self._handle_response(throw_exception=throw_exception)
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_rest_api/manager.py", line 535, in _handle_response
    raise BinanceAPIException(self.response)
unicorn_binance_rest_api.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.

**Comment by AutoAuto** [comment]
@oliver-zehentleitner Is there any update on this issue ? We can observe this problem quite offten, we use unicorn binance websocket with around 120 websockets active, it apears from time to time

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: kuiCRZQMrhTDV8UuorzlwwIUACVGVU06iXyDcgZ-5OUkegdZvUB8Mg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>


is it because of binance limits ?

**Comment by oliver-zehentleitner** [comment]
I dont think its a binance issue.

" Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. " indicates that there is an error between binance and cloudfront.

We can catch the error and retry after a specific time, so the thread will not get broken anymore.

I have never had this issue, maybe its a solution to switch to an other api address (alternate api frontend) within UBRA.

Could you provide me a full debug log beginning 10 min before this error occurs? I could find there some previous error responses from binance that could give us a hint what exactly is going on.

**Comment by oliver-zehentleitner** [comment]
I close this for now. If there are furthere needs please post.
