### ISSUE TITLE
user data crashing

### ISSUE THREAD

**Issue by aleangelin88** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#361]
### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Version of this library.

unicorn-binance-rest-api      1.10.0
unicorn-binance-websocket-api 2.0.0
unicorn-fy                    0.12.2

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.7

### Logging output

```shell
Retrieving all assets - Success
Getting margin fees - Success
Entering data stream
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
Exception in thread frequent_checks:
Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
Exception in thread frequent_checks:
Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    sock = connection.create_connection(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

The above exception was the direct cause of the following exception:

socket.gaierror: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):

The above exception was the direct cause of the following exception:

  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
    response = self._make_request(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    raise new_e
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    self._validate_conn(conn)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 611, in connect
    conn.connect()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    self.sock = sock = self._new_conn()
    raise NameResolutionError(self.host, self, e) from e
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001FCFDAC29D0>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 486, in send
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001FCFDAC2C10>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    resp = conn.urlopen(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    retries = retries.increment(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCFDAC29D0>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCFDAC2C10>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    self.run()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "unicorn_binance_websocket_api\\manager.py", line 804, in unicorn_binance_websocket_api.manager.BinanceWebSocketApiManager._frequent_checks
    self.run()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
  File "unicorn_binance_websocket_api\\restclient.py", line 293, in unicorn_binance_websocket_api.restclient.BinanceWebSocketApiRestclient.keepalive_listen_key
    self._target(*self._args, **self._kwargs)
  File "unicorn_binance_websocket_api\\manager.py", line 804, in unicorn_binance_websocket_api.manager.BinanceWebSocketApiManager._frequent_checks
  File "unicorn_binance_websocket_api\\restclient.py", line 295, in unicorn_binance_websocket_api.restclient.BinanceWebSocketApiRestclient.keepalive_listen_key
  File "unicorn_binance_websocket_api\\restclient.py", line 293, in unicorn_binance_websocket_api.restclient.BinanceWebSocketApiRestclient.keepalive_listen_key
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 370, in __init__
  File "unicorn_binance_websocket_api\\restclient.py", line 295, in unicorn_binance_websocket_api.restclient.BinanceWebSocketApiRestclient.keepalive_listen_key
    self.ping()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 769, in ping
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 370, in __init__
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 542, in _get
    self.ping()
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 769, in ping
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 494, in _request_api
    return self._request(method, uri, signed, throw_exception=throw_exception, **kwargs)
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 487, in _request
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 542, in _get
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 602, in get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 494, in _request_api
    return self.request("GET", url, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 589, in request
    return self._request(method, uri, signed, throw_exception=throw_exception, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn_binance_rest_api\manager.py", line 487, in _request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 703, in send
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 519, in send
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 703, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCFDAC29D0>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)"))
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FCFDAC2C10>: Failed to resolve 'api.binance.com' ([Errno 11001] getaddrinfo failed)"))
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
spot {"e":"executionReport","E":1699899792957,"s":"BNTUSDT","c":null,"S":"SELL","o":"LIMIT_MAKER","f":"GTC","q":"29.10000000","p":"1.02990000","P":"0.00000000","F":"0.00000000","g":94115953,"C":"manual_G","x":"EXPIRED","X":"EXPIRED","r":"NONE","i":422661725,"l":"0.00000000","z":"0.00000000","L":"0.00000000","n":"0","N":null,"T":1699899792957,"t":-1,"I":867453312,"w":false,"m":false,"M":false,"O":1699863002060,"Z":"0.00000000","Y":"0.00000000","Q":"0.00000000","W":1699863002060,"V":"EXPIRE_MAKER"}
spot {"e":"executionReport","E":1699899792957,"s":"BNTUSDT","c":"manual_L","S":"SELL","o":"STOP_LOSS_LIMIT","f":"GTC","q":"29.10000000","p":"0.75420000","P":"0.00000000","d":750,"F":"0.00000000","g":94115953,"C":"","x":"NEW","X":"NEW","r":"NONE","i":422661724,"l":"0.00000000","z":"0.00000000","L":"0.00000000","n":"0","N":null,"T":1699899792957,"t":-1,"I":867453313,"w":true,"m":false,"M":false,"O":1699863002060,"Z":"0.00000000","Y":"0.00000000","Q":"0.00000000","D":1699863002060,"W":1699899792957,"V":"EXPIRE_MAKER"}
spot {"e":"executionReport","E":1699899792957,"s":"BNTUSDT","c":"manual_L","S":"SELL","o":"STOP_LOSS_LIMIT","f":"GTC","q":"29.10000000","p":"0.75420000","P":"0.00000000","d":750,"F":"0.00000000","g":94115953,"C":"","x":"TRADE","X":"FILLED","r":"NONE","i":422661724,"l":"29.10000000","z":"29.10000000","L":"0.87830000","n":"0.00007827","N":"BNB","T":1699899792957,"t":18808520,"I":867453314,"w":false,"m":false,"M":true,"O":1699863002060,"Z":"25.55853000","Y":"25.55853000","Q":"0.00000000","D":1699863002060,"W":1699899792957,"V":"EXPIRE_MAKER"}
spot {"e":"listStatus","E":1699899792957,"s":"BNTUSDT","g":94115953,"c":"OCO","l":"ALL_DONE","L":"ALL_DONE","r":"NONE","C":"manual","T":1699899792957,"O":[{"s":"BNTUSDT","i":422661724,"c":"manual_L"},{"s":"BNTUSDT","i":422661725,"c":"manual_G"}]}
spot {"e":"outboundAccountPosition","E":1699899792957,"u":1699899792957,"B":[{"a":"BNB","f":"0.56687795","l":"0.00000000"},{"a":"BNT","f":"0.00000000","l":"0.00000000"},{"a":"USDT","f":"1642.59566061","l":"0.00000000"}]}
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(72e9a033d4e9-34de-0858-ee80-0a3c57a3, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: no close frame received or sent
BinanceWebSocketApiManager.stream_is_crashing(72e9a033d4e9-34de-0858-ee80-0a3c57a3)
BinanceWebSocketApiSocket.start_socket(017c0db1181e-0877-469f-c708-38a0ae60, ['arr'], ['!userData']) - Exception ConnectionClosed - error_msg: no close frame received or sent
BinanceWebSocketApiManager.stream_is_crashing(017c0db1181e-0877-469f-c708-38a0ae60)
```

### Processing method?

stream_buffer

### Used endpoint?

concerns all

### Issue

the script was simply collecting user data information. it seemed to crash, but somehow still getting data

**Comment by oliver-zehentleitner** [comment]
please update:
```
pip install unicorn-binance-websocket-api —upgrade
pip install unicorn-binance-rest-api —upgrade
pip install lucit-licensing-python —upgrade
pip install unicorn-fy —upgrade
```

**Comment by oliver-zehentleitner** [comment]
can we close this?

**Comment by aleangelin88** [comment]
it works now.. thank you
